
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Feb 16 00:18:04 CET 2020
//----------------------------------------------------

package compiler.syntax;

import java_cup.runtime.Symbol;
import java.util.*;
import es.uned.lsi.compiler.lexical.*;
import es.uned.lsi.compiler.code.*;
import es.uned.lsi.compiler.intermediate.*;
import es.uned.lsi.compiler.semantic.*;
import es.uned.lsi.compiler.semantic.symbol.*;
import es.uned.lsi.compiler.semantic.type.*;
import es.uned.lsi.compiler.syntax.*;
import compiler.CompilerContext;
import compiler.lexical.*;
import compiler.syntax.nonTerminal.*;
import compiler.semantic.*;
import compiler.semantic.symbol.*;
import compiler.semantic.type.*;
import compiler.intermediate.*;
import compiler.code.*;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Sun Feb 16 00:18:04 CET 2020
  */
public class parser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\154\000\002\002\004\000\002\050\002\000\002\002" +
    "\004\000\002\003\012\000\002\004\005\000\002\004\003" +
    "\000\002\010\005\000\002\010\003\000\002\017\005\000" +
    "\002\017\003\000\002\022\004\000\002\022\002\000\002" +
    "\005\003\000\002\005\004\000\002\006\006\000\002\007" +
    "\003\000\002\007\003\000\002\007\003\000\002\011\003" +
    "\000\002\011\004\000\002\012\015\000\002\013\003\000" +
    "\002\013\003\000\002\014\003\000\002\014\003\000\002" +
    "\015\003\000\002\015\003\000\002\016\003\000\002\020" +
    "\003\000\002\020\004\000\002\021\006\000\002\021\005" +
    "\000\002\023\003\000\002\023\004\000\002\024\003\000" +
    "\002\024\003\000\002\025\017\000\002\031\016\000\002" +
    "\026\003\000\002\026\002\000\002\027\003\000\002\027" +
    "\005\000\002\030\006\000\002\030\005\000\002\046\003" +
    "\000\002\046\002\000\002\032\005\000\002\032\002\000" +
    "\002\033\003\000\002\033\003\000\002\033\003\000\002" +
    "\033\003\000\002\033\003\000\002\033\003\000\002\033" +
    "\003\000\002\034\005\000\002\037\011\000\002\037\014" +
    "\000\002\047\006\000\002\047\006\000\002\045\004\000" +
    "\002\040\014\000\002\041\006\000\002\042\003\000\002" +
    "\042\003\000\002\042\002\000\002\036\005\000\002\036" +
    "\005\000\002\036\005\000\002\036\005\000\002\036\005" +
    "\000\002\036\004\000\002\036\005\000\002\036\005\000" +
    "\002\036\003\000\002\036\003\000\002\036\003\000\002" +
    "\036\003\000\002\036\003\000\002\035\003\000\002\035" +
    "\006\000\002\035\003\000\002\043\006\000\002\043\006" +
    "\000\002\044\005\000\002\044\005\000\002\044\005\000" +
    "\002\044\005\000\002\044\005\000\002\044\005\000\002" +
    "\044\002\000\002\051\002\000\002\003\013\000\002\052" +
    "\002\000\002\003\012\000\002\053\002\000\002\003\013" +
    "\000\002\054\002\000\002\003\013\000\002\055\002\000" +
    "\002\003\013\000\002\056\002\000\002\004\006\000\002" +
    "\057\002\000\002\010\006\000\002\060\002\000\002\017" +
    "\006\000\002\022\004" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\366\000\006\024\000\055\000\001\002\000\004\002" +
    "\370\001\002\000\006\024\010\055\006\001\002\000\004" +
    "\003\360\001\002\000\004\002\uffff\001\002\000\006\003" +
    "\012\055\011\001\002\000\026\003\ufff6\006\ufff6\007\017" +
    "\020\040\023\022\027\027\030\015\032\026\043\331\055" +
    "\024\001\002\000\022\006\uffa4\007\uffa4\020\uffa4\023\uffa4" +
    "\027\uffa4\030\uffa4\032\uffa4\055\uffa4\001\002\000\022\006" +
    "\ufff6\007\017\020\040\023\022\027\027\030\015\032\026" +
    "\055\024\001\002\000\012\003\uffdf\006\uffdf\020\uffdf\023" +
    "\uffdf\001\002\000\004\055\310\001\002\000\006\003\323" +
    "\055\316\001\002\000\004\055\316\001\002\000\020\003" +
    "\uffef\006\uffef\020\uffef\023\uffef\027\uffef\032\uffef\055\uffef" +
    "\001\002\000\006\003\311\055\310\001\002\000\004\055" +
    "\275\001\002\000\016\003\uffe5\006\uffe5\020\uffe5\023\uffe5" +
    "\027\uffe5\055\uffe5\001\002\000\010\041\246\043\247\052" +
    "\256\001\002\000\006\003\ufffc\006\ufffc\001\002\000\004" +
    "\055\242\001\002\000\006\020\040\023\022\001\002\000" +
    "\006\003\ufffa\006\ufffa\001\002\000\022\003\ufff5\006\ufff5" +
    "\020\ufff5\023\ufff5\027\ufff5\030\ufff5\032\ufff5\055\ufff5\001" +
    "\002\000\006\003\243\055\242\001\002\000\006\003\ufff8" +
    "\006\ufff8\001\002\000\004\006\235\001\002\000\012\003" +
    "\uffde\006\uffde\020\uffde\023\uffde\001\002\000\010\003\233" +
    "\020\040\023\022\001\002\000\012\003\uffe1\006\uffe1\020" +
    "\uffe1\023\uffe1\001\002\000\004\055\041\001\002\000\004" +
    "\035\042\001\002\000\006\036\uffda\055\043\001\002\000" +
    "\006\041\222\043\223\001\002\000\004\036\051\001\002" +
    "\000\006\036\uffdb\042\047\001\002\000\006\036\uffd9\042" +
    "\uffd9\001\002\000\004\055\043\001\002\000\006\036\uffd8" +
    "\042\uffd8\001\002\000\004\043\052\001\002\000\006\004" +
    "\055\013\054\001\002\000\004\043\056\001\002\000\010" +
    "\036\uffe8\042\uffe8\043\uffe8\001\002\000\010\036\uffe7\042" +
    "\uffe7\043\uffe7\001\002\000\022\006\ufff6\007\017\020\040" +
    "\023\022\027\027\030\015\032\026\055\024\001\002\000" +
    "\004\006\060\001\002\000\016\012\074\015\066\017\uffd2" +
    "\022\073\025\076\055\071\001\002\000\004\042\uffd0\001" +
    "\002\000\004\042\uffd1\001\002\000\004\042\220\001\002" +
    "\000\004\052\216\001\002\000\004\042\uffce\001\002\000" +
    "\004\035\211\001\002\000\004\042\uffcd\001\002\000\004" +
    "\042\uffcb\001\002\000\034\014\uffb2\034\uffb2\035\173\036" +
    "\uffb2\037\150\040\uffb2\041\uffb2\042\uffb2\046\uffb2\047\uffb2" +
    "\050\uffb2\051\uffb2\052\uffb2\001\002\000\006\042\uffcc\052" +
    "\uffb0\001\002\000\006\053\154\055\161\001\002\000\004" +
    "\055\145\001\002\000\004\017\143\001\002\000\020\005" +
    "\102\016\101\021\106\035\104\037\111\053\100\055\071" +
    "\001\002\000\004\042\uffcf\001\002\000\024\014\uffb5\034" +
    "\uffb5\036\uffb5\040\uffb5\042\uffb5\046\uffb5\047\uffb5\050\uffb5" +
    "\051\uffb5\001\002\000\024\014\uffb3\034\uffb3\036\uffb3\040" +
    "\uffb3\042\uffb3\046\uffb3\047\uffb3\050\uffb3\051\uffb3\001\002" +
    "\000\024\014\uffb4\034\uffb4\036\uffb4\040\uffb4\042\uffb4\046" +
    "\uffb4\047\uffb4\050\uffb4\051\uffb4\001\002\000\024\014\uffb6" +
    "\034\uffb6\036\uffb6\040\uffb6\042\uffb6\046\uffb6\047\uffb6\050" +
    "\uffb6\051\uffb6\001\002\000\020\005\102\016\101\021\106" +
    "\035\104\037\111\053\100\055\071\001\002\000\024\014" +
    "\uffb7\034\uffb7\036\uffb7\040\uffb7\042\uffb7\046\uffb7\047\uffb7" +
    "\050\uffb7\051\uffb7\001\002\000\020\005\102\016\101\021" +
    "\106\035\104\037\111\053\100\055\071\001\002\000\016" +
    "\014\126\034\120\046\115\047\116\050\113\051\114\001" +
    "\002\000\026\014\uffb0\034\uffb0\036\uffb0\040\uffb0\041\uffb0" +
    "\042\uffb0\046\uffb0\047\uffb0\050\uffb0\051\uffb0\001\002\000" +
    "\020\005\102\016\101\021\106\035\104\037\111\053\100" +
    "\055\071\001\002\000\016\034\120\040\117\046\115\047" +
    "\116\050\113\051\114\001\002\000\020\005\102\016\101" +
    "\021\106\035\104\037\111\053\100\055\071\001\002\000" +
    "\020\005\102\016\101\021\106\035\104\037\111\053\100" +
    "\055\071\001\002\000\020\005\102\016\101\021\106\035" +
    "\104\037\111\053\100\055\071\001\002\000\020\005\102" +
    "\016\101\021\106\035\104\037\111\053\100\055\071\001" +
    "\002\000\024\014\uffb8\034\uffb8\036\uffb8\040\uffb8\042\uffb8" +
    "\046\uffb8\047\uffb8\050\uffb8\051\uffb8\001\002\000\020\005" +
    "\102\016\101\021\106\035\104\037\111\053\100\055\071" +
    "\001\002\000\024\014\uffbb\034\uffbb\036\uffbb\040\uffbb\042" +
    "\uffbb\046\uffbb\047\uffbb\050\113\051\114\001\002\000\024" +
    "\014\uffbe\034\120\036\uffbe\040\uffbe\042\uffbe\046\115\047" +
    "\uffbe\050\113\051\114\001\002\000\024\014\uffbf\034\120" +
    "\036\uffbf\040\uffbf\042\uffbf\046\uffbf\047\uffbf\050\113\051" +
    "\114\001\002\000\024\014\uffbd\034\uffbd\036\uffbd\040\uffbd" +
    "\042\uffbd\046\uffbd\047\uffbd\050\uffbd\051\uffbd\001\002\000" +
    "\024\014\uffbc\034\uffbc\036\uffbc\040\uffbc\042\uffbc\046\uffbc" +
    "\047\uffbc\050\uffbc\051\114\001\002\000\004\043\127\001" +
    "\002\000\020\012\074\015\066\017\uffd2\022\073\025\076" +
    "\026\uffd2\055\071\001\002\000\006\017\131\026\132\001" +
    "\002\000\004\025\137\001\002\000\004\043\133\001\002" +
    "\000\016\012\074\015\066\017\uffd2\022\073\025\076\055" +
    "\071\001\002\000\004\017\135\001\002\000\004\025\136" +
    "\001\002\000\004\042\uffc8\001\002\000\004\042\uffc9\001" +
    "\002\000\024\014\uffba\034\uffba\036\uffba\040\uffba\042\uffba" +
    "\046\uffba\047\uffba\050\uffba\051\uffba\001\002\000\016\034" +
    "\120\036\142\046\115\047\116\050\113\051\114\001\002" +
    "\000\024\014\uffb9\034\uffb9\036\uffb9\040\uffb9\042\uffb9\046" +
    "\uffb9\047\uffb9\050\uffb9\051\uffb9\001\002\000\004\042\144" +
    "\001\002\000\012\003\uffdd\006\uffdd\020\uffdd\023\uffdd\001" +
    "\002\000\014\035\147\036\uffb2\037\150\041\uffb2\042\uffb2" +
    "\001\002\000\004\042\uffc5\001\002\000\020\005\102\016" +
    "\101\021\106\035\104\037\111\053\100\055\071\001\002" +
    "\000\006\053\154\055\151\001\002\000\006\037\150\040" +
    "\uffeb\001\002\000\004\040\156\001\002\000\004\040\155" +
    "\001\002\000\012\011\uffec\040\uffec\043\uffec\044\uffec\001" +
    "\002\000\030\014\uffc7\034\uffc7\036\uffc7\040\uffc7\041\uffc7" +
    "\042\uffc7\046\uffc7\047\uffc7\050\uffc7\051\uffc7\052\uffc7\001" +
    "\002\000\030\014\uffc6\034\uffc6\036\uffc6\040\uffc6\041\uffc6" +
    "\042\uffc6\046\uffc6\047\uffc6\050\uffc6\051\uffc6\052\uffc6\001" +
    "\002\000\016\034\120\036\160\046\115\047\116\050\113" +
    "\051\114\001\002\000\030\014\uffb1\034\uffb1\036\uffb1\040" +
    "\uffb1\041\uffb1\042\uffb1\046\uffb1\047\uffb1\050\uffb1\051\uffb1" +
    "\052\uffb1\001\002\000\012\011\uffeb\040\uffeb\043\uffeb\044" +
    "\uffeb\001\002\000\004\011\163\001\002\000\006\053\154" +
    "\055\161\001\002\000\004\044\165\001\002\000\006\053" +
    "\154\055\161\001\002\000\004\043\167\001\002\000\016" +
    "\012\074\015\066\017\uffd2\022\073\025\076\055\071\001" +
    "\002\000\004\017\171\001\002\000\004\022\172\001\002" +
    "\000\004\042\uffc4\001\002\000\022\005\102\016\101\021" +
    "\106\035\104\036\uffa7\037\111\053\174\055\071\001\002" +
    "\000\020\034\uffb5\036\uffb5\041\205\046\uffb5\047\uffb5\050" +
    "\uffb5\051\uffb5\001\002\000\020\034\uffb6\036\201\041\200" +
    "\046\uffb6\047\uffb6\050\uffb6\051\uffb6\001\002\000\004\036" +
    "\177\001\002\000\024\014\uffae\034\uffae\036\uffae\040\uffae" +
    "\042\uffae\046\uffae\047\uffae\050\uffae\051\uffae\001\002\000" +
    "\010\036\uffa7\053\204\055\145\001\002\000\024\014\uffaf" +
    "\034\uffaf\036\uffaf\040\uffaf\042\uffaf\046\uffaf\047\uffaf\050" +
    "\uffaf\051\uffaf\001\002\000\004\036\uffac\001\002\000\006" +
    "\036\uffad\041\200\001\002\000\006\036\uffab\041\205\001" +
    "\002\000\010\036\uffa7\053\210\055\145\001\002\000\004" +
    "\036\uffa8\001\002\000\006\036\uffa9\041\200\001\002\000" +
    "\006\036\uffaa\041\205\001\002\000\024\005\102\016\101" +
    "\021\106\035\104\036\uffc0\037\111\053\100\054\213\055" +
    "\071\001\002\000\004\036\215\001\002\000\004\036\uffc1" +
    "\001\002\000\016\034\120\036\uffc2\046\115\047\116\050" +
    "\113\051\114\001\002\000\004\042\uffc3\001\002\000\020" +
    "\005\102\016\101\021\106\035\104\037\111\053\100\055" +
    "\071\001\002\000\016\034\120\042\uffca\046\115\047\116" +
    "\050\113\051\114\001\002\000\022\003\uffd2\012\074\015" +
    "\066\017\uffd2\022\073\025\076\026\uffd2\055\071\001\002" +
    "\000\010\003\uffd3\017\uffd3\026\uffd3\001\002\000\004\055" +
    "\043\001\002\000\012\004\uffd4\013\uffd4\031\224\055\uffd4" +
    "\001\002\000\010\004\uffd5\013\uffd5\055\uffd5\001\002\000" +
    "\010\004\055\013\054\055\226\001\002\000\006\036\uffe6" +
    "\042\uffe6\001\002\000\006\036\uffd7\042\uffd7\001\002\000" +
    "\006\036\uffea\042\uffea\001\002\000\006\036\uffe9\042\uffe9" +
    "\001\002\000\006\036\uffd6\042\uffd6\001\002\000\006\003" +
    "\uff96\006\uff96\001\002\000\012\003\uffe0\006\uffe0\020\uffe0" +
    "\023\uffe0\001\002\000\016\012\074\015\066\017\uffd2\022" +
    "\073\025\076\055\071\001\002\000\004\017\237\001\002" +
    "\000\004\045\240\001\002\000\004\002\uffa3\001\002\000" +
    "\016\003\uffe4\006\uffe4\020\uffe4\023\uffe4\027\uffe4\055\uffe4" +
    "\001\002\000\006\041\246\043\247\001\002\000\014\003" +
    "\uff98\006\uff98\020\uff98\023\uff98\027\uff98\001\002\000\014" +
    "\003\ufff6\006\ufff6\020\040\023\022\027\027\001\002\000" +
    "\006\003\uff97\006\uff97\001\002\000\004\055\242\001\002" +
    "\000\010\004\055\013\054\055\226\001\002\000\004\042" +
    "\251\001\002\000\016\003\uffe3\006\uffe3\020\uffe3\023\uffe3" +
    "\027\uffe3\055\uffe3\001\002\000\016\003\uffe2\006\uffe2\020" +
    "\uffe2\023\uffe2\027\uffe2\055\uffe2\001\002\000\012\003\ufff7" +
    "\006\ufff7\020\040\023\022\001\002\000\016\003\ufff6\006" +
    "\ufff6\020\040\023\022\027\027\055\242\001\002\000\006" +
    "\003\ufff9\006\ufff9\001\002\000\012\005\260\016\262\033" +
    "\257\053\263\001\002\000\004\037\265\001\002\000\004" +
    "\042\ufff1\001\002\000\004\042\264\001\002\000\004\042" +
    "\ufff0\001\002\000\004\042\ufff2\001\002\000\022\003\ufff3" +
    "\006\ufff3\020\ufff3\023\ufff3\027\ufff3\030\ufff3\032\ufff3\055" +
    "\ufff3\001\002\000\006\053\154\055\161\001\002\000\004" +
    "\044\267\001\002\000\006\053\154\055\161\001\002\000" +
    "\004\040\271\001\002\000\004\010\272\001\002\000\006" +
    "\004\055\013\054\001\002\000\004\042\274\001\002\000" +
    "\020\003\uffed\006\uffed\020\uffed\023\uffed\027\uffed\032\uffed" +
    "\055\uffed\001\002\000\004\035\276\001\002\000\004\031" +
    "\277\001\002\000\006\036\uffda\055\043\001\002\000\004" +
    "\036\301\001\002\000\004\043\302\001\002\000\022\006" +
    "\ufff6\007\017\020\040\023\022\027\027\030\015\032\026" +
    "\055\024\001\002\000\004\006\304\001\002\000\016\012" +
    "\074\015\066\017\uffd2\022\073\025\076\055\071\001\002" +
    "\000\004\017\306\001\002\000\004\042\307\001\002\000" +
    "\012\003\uffdc\006\uffdc\020\uffdc\023\uffdc\001\002\000\004" +
    "\052\315\001\002\000\020\003\uff9a\006\uff9a\020\uff9a\023" +
    "\uff9a\027\uff9a\032\uff9a\055\uff9a\001\002\000\020\003\uffee" +
    "\006\uffee\020\uffee\023\uffee\027\uffee\032\uffee\055\uffee\001" +
    "\002\000\020\003\ufff6\006\ufff6\020\040\023\022\027\027" +
    "\032\026\055\242\001\002\000\006\003\uff99\006\uff99\001" +
    "\002\000\004\033\257\001\002\000\004\052\322\001\002" +
    "\000\022\003\ufff6\006\ufff6\020\040\023\022\027\027\030" +
    "\015\032\026\055\024\001\002\000\006\003\ufffd\006\ufffd" +
    "\001\002\000\022\003\ufff4\006\ufff4\020\ufff4\023\ufff4\027" +
    "\ufff4\030\ufff4\032\ufff4\055\ufff4\001\002\000\010\005\260" +
    "\016\262\053\263\001\002\000\022\003\uff9c\006\uff9c\020" +
    "\uff9c\023\uff9c\027\uff9c\030\uff9c\032\uff9c\055\uff9c\001\002" +
    "\000\022\003\ufff6\006\ufff6\020\040\023\022\027\027\030" +
    "\015\032\026\055\326\001\002\000\006\003\uff9b\006\uff9b" +
    "\001\002\000\010\041\246\043\247\052\315\001\002\000" +
    "\020\003\ufff6\006\ufff6\020\040\023\022\027\027\032\026" +
    "\055\326\001\002\000\006\003\ufffb\006\ufffb\001\002\000" +
    "\022\006\ufff6\007\017\020\040\023\022\027\027\030\015" +
    "\032\026\055\024\001\002\000\006\003\333\006\334\001" +
    "\002\000\004\006\uffa2\001\002\000\020\003\uffd2\012\074" +
    "\015\066\017\uffd2\022\073\025\076\055\071\001\002\000" +
    "\006\003\336\017\337\001\002\000\004\017\uffa0\001\002" +
    "\000\004\003\340\001\002\000\004\045\uff9e\001\002\000" +
    "\004\045\342\001\002\000\004\002\uff9d\001\002\000\004" +
    "\017\344\001\002\000\004\045\345\001\002\000\004\002" +
    "\uff9f\001\002\000\004\006\347\001\002\000\016\012\074" +
    "\015\066\017\uffd2\022\073\025\076\055\071\001\002\000" +
    "\004\017\351\001\002\000\004\045\352\001\002\000\004" +
    "\002\uffa1\001\002\000\004\006\354\001\002\000\016\012" +
    "\074\015\066\017\uffd2\022\073\025\076\055\071\001\002" +
    "\000\004\017\356\001\002\000\004\045\357\001\002\000" +
    "\004\002\ufffe\001\002\000\004\043\uffa6\001\002\000\004" +
    "\043\362\001\002\000\022\006\ufff6\007\017\020\040\023" +
    "\022\027\027\030\015\032\026\055\024\001\002\000\004" +
    "\006\364\001\002\000\016\012\074\015\066\017\uffd2\022" +
    "\073\025\076\055\071\001\002\000\004\017\366\001\002" +
    "\000\004\045\367\001\002\000\004\002\uffa5\001\002\000" +
    "\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\366\000\006\002\003\050\004\001\001\000\002\001" +
    "\001\000\004\003\006\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\036\004\331\005\015\006" +
    "\030\010\024\011\020\012\017\017\027\020\031\021\022" +
    "\022\032\023\035\024\036\025\013\031\034\001\001\000" +
    "\004\052\012\001\001\000\036\004\033\005\015\006\030" +
    "\010\024\011\020\012\017\017\027\020\031\021\022\022" +
    "\032\023\035\024\036\025\013\031\034\001\001\000\002" +
    "\001\001\000\006\011\326\012\017\001\001\000\004\006" +
    "\320\001\001\000\006\005\316\006\030\001\001\000\002" +
    "\001\001\000\004\012\311\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\020\253\021\022\001\001\000\012\023\252\024\036\025" +
    "\013\031\034\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\021\240\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\010\024\233\025\013\031\034" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\010\026\043\027\044\030\045\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\030\047\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\015\052\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\036\004\056\005\015" +
    "\006\030\010\024\011\020\012\017\017\027\020\031\021" +
    "\022\022\032\023\035\024\036\025\013\031\034\001\001" +
    "\000\002\001\001\000\026\032\074\033\062\034\061\035" +
    "\063\037\060\040\076\041\064\043\066\045\067\047\071" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\013\161\001\001\000\006\035\145" +
    "\047\107\001\001\000\002\001\001\000\012\035\102\036" +
    "\106\043\104\047\107\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\012\035\102\036\140\043\104\047\107\001\001" +
    "\000\002\001\001\000\012\035\102\036\137\043\104\047" +
    "\107\001\001\000\002\001\001\000\002\001\001\000\012" +
    "\035\102\036\111\043\104\047\107\001\001\000\002\001" +
    "\001\000\012\035\102\036\124\043\104\047\107\001\001" +
    "\000\012\035\102\036\123\043\104\047\107\001\001\000" +
    "\012\035\102\036\122\043\104\047\107\001\001\000\012" +
    "\035\102\036\121\043\104\047\107\001\001\000\002\001" +
    "\001\000\012\035\102\036\120\043\104\047\107\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\026" +
    "\032\127\033\062\034\061\035\063\037\060\040\076\041" +
    "\064\043\066\045\067\047\071\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\026\032\133\033" +
    "\062\034\061\035\063\037\060\040\076\041\064\043\066" +
    "\045\067\047\071\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\012" +
    "\035\102\036\156\043\104\047\107\001\001\000\006\013" +
    "\152\047\151\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\013\163\001\001\000" +
    "\002\001\001\000\004\013\165\001\001\000\002\001\001" +
    "\000\026\032\167\033\062\034\061\035\063\037\060\040" +
    "\076\041\064\043\066\045\067\047\071\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\014\035" +
    "\174\036\156\043\104\044\175\047\107\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\010\035\202\044\201\047\107\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\010\035\206\044\205\047\107\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\014\035" +
    "\102\036\213\042\211\043\104\047\107\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\012\035\102\036\216\043\104\047\107\001\001" +
    "\000\002\001\001\000\026\032\220\033\062\034\061\035" +
    "\063\037\060\040\076\041\064\043\066\045\067\047\071" +
    "\001\001\000\002\001\001\000\004\030\231\001\001\000" +
    "\004\046\224\001\001\000\002\001\001\000\010\014\226" +
    "\015\227\016\230\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\026\032\235\033" +
    "\062\034\061\035\063\037\060\040\076\041\064\043\066" +
    "\045\067\047\071\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\060\243\001\001\000\014\022\244\023\035\024" +
    "\036\025\013\031\034\001\001\000\002\001\001\000\004" +
    "\021\251\001\001\000\010\014\247\015\227\016\230\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\010\024\233\025\013\031\034\001\001\000\016\021" +
    "\240\022\254\023\035\024\036\025\013\031\034\001\001" +
    "\000\002\001\001\000\004\007\260\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\013\265\001" +
    "\001\000\002\001\001\000\004\013\267\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\015\272\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\010\026\277\027\044\030\045\001\001\000" +
    "\002\001\001\000\002\001\001\000\036\004\302\005\015" +
    "\006\030\010\024\011\020\012\017\017\027\020\031\021" +
    "\022\022\032\023\035\024\036\025\013\031\034\001\001" +
    "\000\002\001\001\000\026\032\304\033\062\034\061\035" +
    "\063\037\060\040\076\041\064\043\066\045\067\047\071" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\057\312\001\001\000\002" +
    "\001\001\000\022\017\313\020\031\021\022\022\032\023" +
    "\035\024\036\025\013\031\034\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\032\006\320\010" +
    "\317\011\020\012\017\017\027\020\031\021\022\022\032" +
    "\023\035\024\036\025\013\031\034\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\007\260\001\001\000\004" +
    "\056\323\001\001\000\030\010\324\011\020\012\017\017" +
    "\027\020\031\021\022\022\032\023\035\024\036\025\013" +
    "\031\034\001\001\000\002\001\001\000\002\001\001\000" +
    "\024\012\311\017\327\020\031\021\022\022\032\023\035" +
    "\024\036\025\013\031\034\001\001\000\002\001\001\000" +
    "\036\004\352\005\015\006\030\010\024\011\020\012\017" +
    "\017\027\020\031\021\022\022\032\023\035\024\036\025" +
    "\013\031\034\001\001\000\002\001\001\000\004\053\345" +
    "\001\001\000\026\032\334\033\062\034\061\035\063\037" +
    "\060\040\076\041\064\043\066\045\067\047\071\001\001" +
    "\000\002\001\001\000\004\054\342\001\001\000\002\001" +
    "\001\000\004\055\340\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\026\032\347\033\062\034\061" +
    "\035\063\037\060\040\076\041\064\043\066\045\067\047" +
    "\071\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\026\032\354\033\062\034" +
    "\061\035\063\037\060\040\076\041\064\043\066\045\067" +
    "\047\071\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\051\360\001\001\000\002\001\001" +
    "\000\036\004\362\005\015\006\030\010\024\011\020\012" +
    "\017\017\027\020\031\021\022\022\032\023\035\024\036" +
    "\025\013\031\034\001\001\000\002\001\001\000\026\032" +
    "\364\033\062\034\061\035\063\037\060\040\076\041\064" +
    "\043\066\045\067\047\071\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



	SyntaxErrorManager syntaxErrorManager = CompilerContext.getSyntaxErrorManager();
	
	public void syntax_error(Symbol symbol)
	{ 
	    Token token = (Token) symbol.value;
	    syntaxErrorManager.syntaxError ("Error sintactico", token);	    
	}
		
	public void unrecovered_syntax_error(java_cup.runtime.Symbol symbol)
	{	
	    Token token = (Token) symbol.value;
	    syntaxErrorManager.syntaxFatalError ("Error fatal", token);
	}

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$parser$actions {


	
	SyntaxErrorManager   syntaxErrorManager   = CompilerContext.getSyntaxErrorManager();
	SemanticErrorManager semanticErrorManager = CompilerContext.getSemanticErrorManager ();
	ScopeManagerIF       scopeManager         = CompilerContext.getScopeManager ();
	FinalCodeFactoryIF   finalCodeFactory     = CompilerContext.getFinalCodeFactory ();


  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 107: // declaracionResto ::= declaracionSubprogramas error 
            {
              Object RESULT =null;
		 syntaxErrorManager.syntaxInfo ("ERROR SINTÁCTICO: Se esperaba la palabra reservada 'variables'."); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionResto",16, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 106: // declaracionVariablesSubprogramas ::= declaracionVariables error NT$8 declaracionResto 
            {
              Object RESULT =null;
              // propagate RESULT from NT$8
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionVariablesSubprogramas",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 105: // NT$8 ::= 
            {
              Object RESULT =null;
 syntaxErrorManager.syntaxInfo ("ERROR SINTÁCTICO: Se esperaba la palabra reservada 'variables'."); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$8",46, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 104: // declaracionTiposVariables ::= declaracionTipos error NT$7 declaracionVariablesSubprogramas 
            {
              Object RESULT =null;
              // propagate RESULT from NT$7
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionTiposVariables",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 103: // NT$7 ::= 
            {
              Object RESULT =null;
 syntaxErrorManager.syntaxInfo ("ERROR SINTÁCTICO: Se esperaba la palabra reservada 'tipos'."); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$7",45, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 102: // declaraciones ::= declaracionConstantes error NT$6 declaracionTiposVariables 
            {
              Object RESULT =null;
              // propagate RESULT from NT$6
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaraciones",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 101: // NT$6 ::= 
            {
              Object RESULT =null;
 syntaxErrorManager.syntaxInfo ("ERROR SINTÁCTICO: Se esperaba la palabra reservada 'constantes'."); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$6",44, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 100: // axiom ::= PROGRAMA ID declaraciones COMIENZO sentencias FIN error NT$5 PUNTO 
            {
              Axiom RESULT =null;
              // propagate RESULT from NT$5
                RESULT = (Axiom) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("axiom",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 99: // NT$5 ::= 
            {
              Axiom RESULT =null;
 syntaxErrorManager.syntaxInfo ("ERROR SINTÁCTICO: Se esperaba un punto ('.')."); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$5",43, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 98: // axiom ::= PROGRAMA ID declaraciones COMIENZO sentencias error NT$4 FIN PUNTO 
            {
              Axiom RESULT =null;
              // propagate RESULT from NT$4
                RESULT = (Axiom) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("axiom",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 97: // NT$4 ::= 
            {
              Axiom RESULT =null;
 syntaxErrorManager.syntaxInfo ("ERROR SINTÁCTICO: Se esperaba la palabra reservada 'fin'."); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$4",42, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 96: // axiom ::= PROGRAMA ID declaraciones error NT$3 COMIENZO sentencias FIN PUNTO 
            {
              Axiom RESULT =null;
              // propagate RESULT from NT$3
                RESULT = (Axiom) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("axiom",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 95: // NT$3 ::= 
            {
              Axiom RESULT =null;
 syntaxErrorManager.syntaxInfo ("ERROR SINTÁCTICO: Se esperaba la palabra reservada 'comienzo'."); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$3",41, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 94: // axiom ::= PROGRAMA error NT$2 declaraciones COMIENZO sentencias FIN PUNTO 
            {
              Axiom RESULT =null;
              // propagate RESULT from NT$2
                RESULT = (Axiom) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("axiom",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 93: // NT$2 ::= 
            {
              Axiom RESULT =null;
 syntaxErrorManager.syntaxInfo ("ERROR SINTÁCTICO: ID incorrecto."); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$2",40, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 92: // axiom ::= ID error NT$1 DOS_PUNTOS declaraciones COMIENZO sentencias FIN PUNTO 
            {
              Axiom RESULT =null;
              // propagate RESULT from NT$1
                RESULT = (Axiom) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-6)).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("axiom",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 91: // NT$1 ::= 
            {
              Axiom RESULT =null;
 syntaxErrorManager.syntaxInfo ("ERROR SINTÁCTICO: Se esperaba la palabra reservada 'programa'."); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$1",39, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 90: // parametrosActuales ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("parametrosActuales",34, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 89: // parametrosActuales ::= INT COMA parametrosActuales 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("parametrosActuales",34, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 88: // parametrosActuales ::= INT COMA referencia 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("parametrosActuales",34, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 87: // parametrosActuales ::= INT COMA INT 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("parametrosActuales",34, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 86: // parametrosActuales ::= referencia COMA INT 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("parametrosActuales",34, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 85: // parametrosActuales ::= referencia COMA parametrosActuales 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("parametrosActuales",34, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 84: // parametrosActuales ::= referencia COMA referencia 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("parametrosActuales",34, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 83: // llamadaProcedimientos ::= ID PARENTESIS_IZQ parametrosActuales PARENTESIS_DER 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("llamadaProcedimientos",33, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 82: // llamadaProcedimientos ::= ID PARENTESIS_IZQ referencia PARENTESIS_DER 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("llamadaProcedimientos",33, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 81: // referencia ::= accesoVectores 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("referencia",27, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 80: // referencia ::= ID PARENTESIS_IZQ expresion PARENTESIS_DER 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("referencia",27, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 79: // referencia ::= ID 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("referencia",27, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 78: // expresion ::= FALSO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",28, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 77: // expresion ::= CIERTO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",28, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 76: // expresion ::= INT 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",28, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // expresion ::= referencia 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",28, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // expresion ::= llamadaProcedimientos 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",28, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // expresion ::= CORCHETE_IZQ expresion CORCHETE_DER 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",28, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // expresion ::= PARENTESIS_IZQ expresion PARENTESIS_DER 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",28, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // expresion ::= NO expresion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",28, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // expresion ::= expresion Y expresion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",28, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // expresion ::= expresion MENOR_QUE expresion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",28, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // expresion ::= expresion IGUAL_QUE expresion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",28, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // expresion ::= expresion PRODUCTO expresion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",28, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // expresion ::= expresion SUMA expresion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",28, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // parametro ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("parametro",32, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // parametro ::= STRING 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("parametro",32, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // parametro ::= expresion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("parametro",32, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // sentenciaSalida ::= ESCRIBIR PARENTESIS_IZQ parametro PARENTESIS_DER 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentenciaSalida",31, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // sentenciaPara ::= PARA constanteEntera EN constanteEntera RANGO constanteEntera DOS_PUNTOS sentencias FIN PARA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentenciaPara",30, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-9)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // sentenciaDevolver ::= DEVOLVER referencia 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentenciaDevolver",35, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // accesoVectores ::= ID CORCHETE_IZQ accesoVectores CORCHETE_DER 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("accesoVectores",37, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // accesoVectores ::= ID CORCHETE_IZQ constanteEntera CORCHETE_DER 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("accesoVectores",37, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // sentenciaSiEntoncesSi ::= SI expresion ENTONCES DOS_PUNTOS sentencias SINO DOS_PUNTOS sentencias FIN SI 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentenciaSiEntoncesSi",29, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-9)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // sentenciaSiEntoncesSi ::= SI expresion ENTONCES DOS_PUNTOS sentencias FIN SI 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentenciaSiEntoncesSi",29, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // sentenciaAsignacion ::= referencia ASIGNACION expresion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentenciaAsignacion",26, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // sentencia ::= sentenciaDevolver 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",25, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // sentencia ::= accesoVectores 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",25, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // sentencia ::= llamadaProcedimientos 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",25, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // sentencia ::= sentenciaSalida 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",25, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // sentencia ::= sentenciaPara 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",25, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // sentencia ::= sentenciaSiEntoncesSi 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",25, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // sentencia ::= sentenciaAsignacion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",25, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // sentencias ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencias",24, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // sentencias ::= sentencia PUNTO_COMA sentencias 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencias",24, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // valorReferencia ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("valorReferencia",36, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // valorReferencia ::= VAR 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("valorReferencia",36, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // declaracionParametro ::= ID COMA declaracionParametro 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionParametro",22, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // declaracionParametro ::= ID DOS_PUNTOS valorReferencia tipoPrimitivoCompuesto 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionParametro",22, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // listaParametros ::= listaParametros PUNTO_COMA declaracionParametro 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("listaParametros",21, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // listaParametros ::= declaracionParametro 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("listaParametros",21, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // parametrosFormales ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("parametrosFormales",20, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // parametrosFormales ::= listaParametros 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("parametrosFormales",20, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // declaracionProcedimiento ::= PROCEDIMIENTO ID PARENTESIS_IZQ VAR parametrosFormales PARENTESIS_DER DOS_PUNTOS declaraciones COMIENZO sentencias FIN PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionProcedimiento",23, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-11)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // declaracionFuncion ::= FUNCION ID PARENTESIS_IZQ parametrosFormales PARENTESIS_DER DOS_PUNTOS tipoPrimitivo DOS_PUNTOS declaraciones COMIENZO sentencias FIN PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionFuncion",19, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-12)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // declaracionSubprograma ::= declaracionProcedimiento 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionSubprograma",18, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // declaracionSubprograma ::= declaracionFuncion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionSubprograma",18, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // declaracionSubprogramas ::= declaracionSubprogramas declaracionSubprograma 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionSubprogramas",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // declaracionSubprogramas ::= declaracionSubprograma 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionSubprogramas",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // declaracionVariable ::= ID COMA declaracionVariable 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionVariable",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // declaracionVariable ::= ID DOS_PUNTOS tipoPrimitivoCompuesto PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionVariable",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // declaracionVariables ::= declaracionVariables declaracionVariable 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionVariables",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // declaracionVariables ::= declaracionVariable 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionVariables",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // tipoCompuesto ::= ID 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipoCompuesto",12, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // tipoPrimitivo ::= BOOLEANO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipoPrimitivo",11, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // tipoPrimitivo ::= ENTERO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipoPrimitivo",11, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // tipoPrimitivoCompuesto ::= tipoCompuesto 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipoPrimitivoCompuesto",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // tipoPrimitivoCompuesto ::= tipoPrimitivo 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipoPrimitivoCompuesto",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // constanteEntera ::= ID 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("constanteEntera",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // constanteEntera ::= INT 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("constanteEntera",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // declaracionTipo ::= ID ASIGNACION VECTOR CORCHETE_IZQ constanteEntera RANGO constanteEntera CORCHETE_DER DE tipoPrimitivo PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionTipo",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-10)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // declaracionTipos ::= declaracionTipos declaracionTipo 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionTipos",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // declaracionTipos ::= declaracionTipo 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionTipos",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // valor ::= FALSO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("valor",5, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // valor ::= CIERTO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("valor",5, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // valor ::= INT 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("valor",5, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // declaracionConstante ::= ID ASIGNACION valor PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionConstante",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // declaracionConstantes ::= declaracionConstantes declaracionConstante 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionConstantes",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // declaracionConstantes ::= declaracionConstante 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionConstantes",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // declaracionResto ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionResto",16, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // declaracionResto ::= SUBPROGRAMAS declaracionSubprogramas 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionResto",16, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // declaracionVariablesSubprogramas ::= declaracionResto 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionVariablesSubprogramas",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // declaracionVariablesSubprogramas ::= VARIABLES declaracionVariables declaracionResto 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionVariablesSubprogramas",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // declaracionTiposVariables ::= declaracionVariablesSubprogramas 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionTiposVariables",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // declaracionTiposVariables ::= TIPOS declaracionTipos declaracionVariablesSubprogramas 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionTiposVariables",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // declaraciones ::= declaracionTiposVariables 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaraciones",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // declaraciones ::= CONSTANTES declaracionConstantes declaracionTiposVariables 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaraciones",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // axiom ::= PROGRAMA ID DOS_PUNTOS declaraciones COMIENZO sentencias FIN PUNTO 
            {
              Axiom RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("axiom",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // program ::= NT$0 axiom 
            {
              Object RESULT =null;
              // propagate RESULT from NT$0
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int axleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int axright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Axiom ax = (Axiom)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
  		// No modificar esta estructura, aunque se pueden añadir más acciones semánticas
  		// Para la entrega de febrero pueden comentarse las dos sentencias siguientes:
  		//List intermediateCode = ax.getIntermediateCode ();
  		//finalCodeFactory.create (intermediateCode);
  		// En caso de no comentarse las sentencias anteriores puede generar una excepcion
  		// en las llamadas a cupTest en la entrega de Febrero. Esto es debido a que 
  		// aún no se tendrá implementada la generación de código intermedio ni final.
  		// Para la entrega de Junio deberán descomentarse y usarse.
  		
  		syntaxErrorManager.syntaxInfo ("Parsing process ended.");
   
              CUP$parser$result = parser.getSymbolFactory().newSymbol("program",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // NT$0 ::= 
            {
              Object RESULT =null;
 
        syntaxErrorManager.syntaxInfo ("Starting parsing..."); 
   
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$0",38, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= program EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

