
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Feb 16 00:18:04 CET 2020
//----------------------------------------------------

package compiler.syntax;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int Y = 26;
  public static final int TIPOS = 22;
  public static final int DE = 6;
  public static final int PARENTESIS_IZQ = 27;
  public static final int DEVOLVER = 8;
  public static final int SUBPROGRAMAS = 21;
  public static final int PROGRAMA = 18;
  public static final int ENTERO = 9;
  public static final int SI = 19;
  public static final int FUNCION = 14;
  public static final int CIERTO = 3;
  public static final int DOS_PUNTOS = 33;
  public static final int CORCHETE_DER = 30;
  public static final int ENTONCES = 10;
  public static final int INT = 41;
  public static final int RANGO = 34;
  public static final int FIN = 13;
  public static final int COMIENZO = 4;
  public static final int SINO = 20;
  public static final int CONSTANTES = 5;
  public static final int ESCRIBIR = 11;
  public static final int PROCEDIMIENTO = 17;
  public static final int SUMA = 36;
  public static final int ID = 43;
  public static final int PUNTO_COMA = 32;
  public static final int EOF = 0;
  public static final int PRODUCTO = 37;
  public static final int PARENTESIS_DER = 28;
  public static final int error = 1;
  public static final int COMA = 31;
  public static final int VECTOR = 25;
  public static final int ASIGNACION = 40;
  public static final int EN = 7;
  public static final int NO = 15;
  public static final int PUNTO = 35;
  public static final int VARIABLES = 24;
  public static final int IGUAL_QUE = 39;
  public static final int CORCHETE_IZQ = 29;
  public static final int FALSO = 12;
  public static final int BOOLEANO = 2;
  public static final int STRING = 42;
  public static final int PARA = 16;
  public static final int MENOR_QUE = 38;
  public static final int VAR = 23;
}

