/* The following code was generated by JFlex 1.4.1 on 16/02/20 00:18 */

package compiler.lexical;
import compiler.syntax.sym;
import compiler.lexical.Token;
import es.uned.lsi.compiler.lexical.ScannerIF;
import es.uned.lsi.compiler.lexical.LexicalError;
import es.uned.lsi.compiler.lexical.LexicalErrorManager;

//Produced by MV tools 2019-11-07 10:52:06
// incluir aqui, si es necesario otras importaciones


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.1
 * on 16/02/20 00:18 from the specification file
 * <tt>D:/Universitat/PL1/ArquitecturaPLI-2019-2020/doc/specs/scanner.flex</tt>
 */
public class Scanner implements java_cup.runtime.Scanner, ScannerIF {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  1,  1,  3,  0,  1,  2,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     1,  0,  7,  6,  0,  0,  0,  0, 28, 29, 37, 36, 32,  0, 35,  0, 
     4,  4,  4,  4,  4,  4,  4,  4,  4,  4, 34, 33, 38, 39,  0,  0, 
     0, 12,  8, 14, 21, 11, 23, 26,  5, 15,  5,  5, 10, 18, 13,  9, 
    25,  5, 16, 20, 17, 24, 22,  5,  5, 27, 19, 30,  0, 31,  0,  0, 
     0, 12,  8, 14, 21, 11, 23, 26,  5, 15,  5,  5, 10, 18, 13,  9, 
    25,  5, 16, 20, 17, 24, 22,  5,  5, 27, 19,  0,  0,  0,  0,  0
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\1\1\3\1\4\2\1\12\4"+
    "\1\5\1\6\1\7\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\3\0\1\22\1\4"+
    "\1\23\1\4\1\24\3\4\1\25\1\4\1\26\7\4"+
    "\1\27\1\30\13\4\1\31\1\4\1\32\13\4\1\33"+
    "\6\4\1\34\11\4\1\35\4\4\1\36\5\4\1\37"+
    "\3\4\1\40\2\4\1\41\14\4\1\42\2\4\1\43"+
    "\1\44\1\45\1\4\1\46\1\4\1\47\2\4\1\50"+
    "\2\4\1\51\1\4\1\52\4\4\1\53\1\4\1\54";

  private static int [] zzUnpackAction() {
    int [] result = new int[152];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\50\0\50\0\120\0\170\0\240\0\310\0\360"+
    "\0\u0118\0\u0140\0\u0168\0\u0190\0\u01b8\0\u01e0\0\u0208\0\u0230"+
    "\0\u0258\0\u0280\0\240\0\50\0\50\0\50\0\50\0\50"+
    "\0\50\0\50\0\u02a8\0\50\0\50\0\50\0\u02d0\0\310"+
    "\0\u02f8\0\360\0\360\0\u0320\0\u0348\0\u0370\0\240\0\u0398"+
    "\0\u03c0\0\u03e8\0\u0410\0\u0438\0\u0460\0\u0488\0\u04b0\0\u04d8"+
    "\0\u0500\0\u0528\0\u0550\0\u0578\0\50\0\50\0\u05a0\0\u05c8"+
    "\0\u05f0\0\u0618\0\u0640\0\u0668\0\u0690\0\u06b8\0\u06e0\0\u0708"+
    "\0\u0730\0\u0758\0\u0780\0\240\0\u07a8\0\u07d0\0\u07f8\0\u0820"+
    "\0\u0848\0\u0870\0\u0898\0\u08c0\0\u08e8\0\u0910\0\u0938\0\240"+
    "\0\u0960\0\u0988\0\u09b0\0\u09d8\0\u0a00\0\u0a28\0\240\0\u0a50"+
    "\0\u0a78\0\u0aa0\0\u0ac8\0\u0af0\0\u0b18\0\u0b40\0\u0b68\0\u0b90"+
    "\0\240\0\u0bb8\0\u0be0\0\u0c08\0\u0c30\0\240\0\u0c58\0\u0c80"+
    "\0\u0ca8\0\u0cd0\0\u0cf8\0\240\0\u0d20\0\u0d48\0\u0d70\0\240"+
    "\0\u0d98\0\u0dc0\0\240\0\u0de8\0\u0e10\0\u0e38\0\u0e60\0\u0e88"+
    "\0\u0eb0\0\u0ed8\0\u0f00\0\u0f28\0\u0f50\0\u0f78\0\u0fa0\0\240"+
    "\0\u0fc8\0\u0ff0\0\240\0\240\0\240\0\u1018\0\240\0\u1040"+
    "\0\240\0\u1068\0\u1090\0\240\0\u10b8\0\u10e0\0\240\0\u1108"+
    "\0\240\0\u1130\0\u1158\0\u1180\0\u11a8\0\240\0\u11d0\0\240";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[152];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\2\1\5\1\6\1\7\1\10"+
    "\1\11\2\6\1\12\1\6\1\13\1\14\2\6\1\15"+
    "\2\6\1\16\1\17\1\20\1\21\1\6\1\22\1\6"+
    "\1\23\1\24\1\25\1\26\1\27\1\30\1\31\1\32"+
    "\1\33\1\34\1\35\1\36\1\37\53\0\1\3\50\0"+
    "\1\5\47\0\2\6\2\0\24\6\14\0\2\40\1\41"+
    "\1\0\44\40\3\42\1\0\3\42\1\43\40\42\4\0"+
    "\2\6\2\0\1\6\1\44\22\6\20\0\2\6\2\0"+
    "\5\6\1\45\6\6\1\46\7\6\20\0\2\6\2\0"+
    "\1\6\1\47\22\6\20\0\2\6\2\0\1\6\1\50"+
    "\5\6\1\51\14\6\20\0\2\6\2\0\7\6\1\52"+
    "\14\6\20\0\2\6\2\0\7\6\1\53\10\6\1\54"+
    "\3\6\20\0\2\6\2\0\3\6\1\55\20\6\20\0"+
    "\2\6\2\0\3\6\1\56\1\57\17\6\20\0\2\6"+
    "\2\0\4\6\1\60\2\6\1\61\10\6\1\62\3\6"+
    "\20\0\2\6\2\0\4\6\1\63\3\6\1\64\13\6"+
    "\57\0\1\65\53\0\1\66\2\40\1\41\1\3\44\40"+
    "\4\0\2\6\2\0\1\6\1\67\22\6\20\0\2\6"+
    "\2\0\11\6\1\70\12\6\20\0\2\6\2\0\6\6"+
    "\1\71\15\6\20\0\2\6\2\0\5\6\1\72\4\6"+
    "\1\73\11\6\20\0\2\6\2\0\3\6\1\74\20\6"+
    "\20\0\2\6\2\0\21\6\1\75\2\6\20\0\2\6"+
    "\2\0\5\6\1\76\16\6\20\0\2\6\2\0\1\77"+
    "\23\6\20\0\2\6\2\0\16\6\1\100\5\6\20\0"+
    "\2\6\2\0\6\6\1\101\15\6\20\0\2\6\2\0"+
    "\10\6\1\102\13\6\20\0\2\6\2\0\2\6\1\103"+
    "\21\6\20\0\2\6\2\0\5\6\1\104\16\6\20\0"+
    "\2\6\2\0\5\6\1\105\16\6\20\0\2\6\2\0"+
    "\10\6\1\106\13\6\20\0\2\6\2\0\1\6\1\107"+
    "\22\6\20\0\2\6\2\0\2\6\1\110\21\6\20\0"+
    "\2\6\2\0\1\6\1\111\1\6\1\112\20\6\20\0"+
    "\2\6\2\0\10\6\1\113\13\6\20\0\2\6\2\0"+
    "\14\6\1\114\7\6\20\0\2\6\2\0\7\6\1\115"+
    "\14\6\20\0\2\6\2\0\10\6\1\116\13\6\20\0"+
    "\2\6\2\0\1\6\1\117\22\6\20\0\2\6\2\0"+
    "\1\6\1\120\22\6\20\0\2\6\2\0\21\6\1\121"+
    "\2\6\20\0\2\6\2\0\1\6\1\122\22\6\20\0"+
    "\2\6\2\0\11\6\1\123\12\6\20\0\2\6\2\0"+
    "\7\6\1\124\14\6\20\0\2\6\2\0\14\6\1\125"+
    "\7\6\20\0\2\6\2\0\6\6\1\126\15\6\20\0"+
    "\2\6\2\0\4\6\1\127\17\6\20\0\2\6\2\0"+
    "\6\6\1\130\13\6\1\131\1\6\20\0\2\6\2\0"+
    "\3\6\1\132\20\6\20\0\2\6\2\0\5\6\1\133"+
    "\16\6\20\0\2\6\2\0\10\6\1\134\13\6\20\0"+
    "\2\6\2\0\7\6\1\135\14\6\20\0\2\6\2\0"+
    "\11\6\1\136\12\6\20\0\2\6\2\0\3\6\1\137"+
    "\20\6\20\0\2\6\2\0\11\6\1\140\12\6\20\0"+
    "\2\6\2\0\14\6\1\141\7\6\20\0\2\6\2\0"+
    "\10\6\1\142\13\6\20\0\2\6\2\0\2\6\1\143"+
    "\21\6\20\0\2\6\2\0\1\6\1\144\22\6\20\0"+
    "\2\6\2\0\4\6\1\145\17\6\20\0\2\6\2\0"+
    "\1\6\1\146\22\6\20\0\2\6\2\0\7\6\1\147"+
    "\14\6\20\0\2\6\2\0\3\6\1\150\20\6\20\0"+
    "\2\6\2\0\10\6\1\151\13\6\20\0\2\6\2\0"+
    "\4\6\1\152\17\6\20\0\2\6\2\0\6\6\1\153"+
    "\15\6\20\0\2\6\2\0\1\6\1\154\22\6\20\0"+
    "\2\6\2\0\1\155\23\6\20\0\2\6\2\0\4\6"+
    "\1\156\17\6\20\0\2\6\2\0\5\6\1\157\16\6"+
    "\20\0\2\6\2\0\1\6\1\160\22\6\20\0\2\6"+
    "\2\0\1\6\1\161\22\6\20\0\2\6\2\0\16\6"+
    "\1\162\5\6\20\0\2\6\2\0\10\6\1\163\13\6"+
    "\20\0\2\6\2\0\1\164\23\6\20\0\2\6\2\0"+
    "\1\6\1\165\22\6\20\0\2\6\2\0\15\6\1\166"+
    "\6\6\20\0\2\6\2\0\4\6\1\167\17\6\20\0"+
    "\2\6\2\0\5\6\1\170\16\6\20\0\2\6\2\0"+
    "\3\6\1\171\20\6\20\0\2\6\2\0\7\6\1\172"+
    "\14\6\20\0\2\6\2\0\5\6\1\173\16\6\20\0"+
    "\2\6\2\0\13\6\1\174\10\6\20\0\2\6\2\0"+
    "\22\6\1\175\1\6\20\0\2\6\2\0\3\6\1\176"+
    "\20\6\20\0\2\6\2\0\2\6\1\177\21\6\20\0"+
    "\2\6\2\0\5\6\1\200\16\6\20\0\2\6\2\0"+
    "\7\6\1\201\14\6\20\0\2\6\2\0\12\6\1\202"+
    "\11\6\20\0\2\6\2\0\1\6\1\203\22\6\20\0"+
    "\2\6\2\0\14\6\1\204\7\6\20\0\2\6\2\0"+
    "\10\6\1\205\13\6\20\0\2\6\2\0\11\6\1\206"+
    "\12\6\20\0\2\6\2\0\1\6\1\207\22\6\20\0"+
    "\2\6\2\0\10\6\1\210\13\6\20\0\2\6\2\0"+
    "\10\6\1\211\13\6\20\0\2\6\2\0\3\6\1\212"+
    "\20\6\20\0\2\6\2\0\12\6\1\213\11\6\20\0"+
    "\2\6\2\0\4\6\1\214\17\6\20\0\2\6\2\0"+
    "\3\6\1\215\20\6\20\0\2\6\2\0\4\6\1\216"+
    "\17\6\20\0\2\6\2\0\14\6\1\217\7\6\20\0"+
    "\2\6\2\0\7\6\1\220\14\6\20\0\2\6\2\0"+
    "\14\6\1\221\7\6\20\0\2\6\2\0\12\6\1\222"+
    "\11\6\20\0\2\6\2\0\3\6\1\223\20\6\20\0"+
    "\2\6\2\0\4\6\1\224\17\6\20\0\2\6\2\0"+
    "\5\6\1\225\16\6\20\0\2\6\2\0\14\6\1\226"+
    "\7\6\20\0\2\6\2\0\11\6\1\227\12\6\20\0"+
    "\2\6\2\0\1\6\1\230\22\6\14\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4600];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\20\1\7\11\1\1\3\11\1\1\3\0"+
    "\22\1\2\11\142\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[152];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
 LexicalErrorManager lexicalErrorManager = new LexicalErrorManager ();
 private int commentCount = 0;
 int linecom=0;
 int columncom=0;
 int contadorstring=0;


 //Funcion para crear tokens

 Token createToken (int x)	{
 	Token token = new Token (x);
 	 token.setLine (yyline + 1);
 	 token.setColumn (yycolumn + 1);
 	 token.setLexema (yytext ());
 	 return token;
}

 LexicalError createError(String mensaje){
	LexicalError error = new LexicalError (mensaje);
	error.setLine (yyline + 1);
	error.setColumn (yycolumn + 1);
	error.setLexema (yytext ());
	lexicalErrorManager.lexicalError (mensaje);
	 return error;
}


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Scanner(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Scanner(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzPushbackPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead < 0) {
      return true;
    }
    else {
      zzEndRead+= numRead;
      return false;
    }
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = zzPushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) throws LexicalError {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new LexicalError(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  throws LexicalError {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException, LexicalError {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = zzLexicalState;


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 42: 
          { return createToken (sym.CONSTANTES);
          }
        case 45: break;
        case 25: 
          { return createToken (sym.VAR);
          }
        case 46: break;
        case 40: 
          { return createToken (sym.PROGRAMA);
          }
        case 47: break;
        case 18: 
          { return createToken (sym.STRING);
          }
        case 48: break;
        case 5: 
          { return createToken (sym.Y);
          }
        case 49: break;
        case 17: 
          { return createToken (sym.ASIGNACION);
          }
        case 50: break;
        case 9: 
          { return createToken (sym.CORCHETE_DER);
          }
        case 51: break;
        case 26: 
          { return createToken (sym.FIN);
          }
        case 52: break;
        case 32: 
          { return createToken (sym.CIERTO);
          }
        case 53: break;
        case 23: 
          { return createToken (sym.RANGO);
          }
        case 54: break;
        case 1: 
          { LexicalError error = new LexicalError ();
		error.setLine (yyline + 1);
		error.setColumn (yycolumn + 1);
		error.setLexema (yytext ());
		lexicalErrorManager.lexicalError (error);
          }
        case 55: break;
        case 34: 
          { return createToken (sym.FUNCION);
          }
        case 56: break;
        case 10: 
          { return createToken (sym.COMA);
          }
        case 57: break;
        case 6: 
          { return createToken (sym.PARENTESIS_IZQ);
          }
        case 58: break;
        case 21: 
          { return createToken (sym.SI);
          }
        case 59: break;
        case 15: 
          { return createToken (sym.PRODUCTO);
          }
        case 60: break;
        case 38: 
          { return createToken (sym.COMIENZO);
          }
        case 61: break;
        case 44: 
          { return createToken (sym.PROCEDIMIENTO);
          }
        case 62: break;
        case 41: 
          { return createToken (sym.VARIABLES);
          }
        case 63: break;
        case 24: 
          { return createToken (sym.IGUAL_QUE);
          }
        case 64: break;
        case 39: 
          { return createToken (sym.DEVOLVER);
          }
        case 65: break;
        case 8: 
          { return createToken (sym.CORCHETE_IZQ);
          }
        case 66: break;
        case 36: 
          { return createToken (sym.ENTONCES);
          }
        case 67: break;
        case 20: 
          { return createToken (sym.NO);
          }
        case 68: break;
        case 12: 
          { return createToken (sym.DOS_PUNTOS);
          }
        case 69: break;
        case 29: 
          { return createToken (sym.TIPOS);
          }
        case 70: break;
        case 22: 
          { return createToken (sym.DE);
          }
        case 71: break;
        case 30: 
          { return createToken (sym.FALSO);
          }
        case 72: break;
        case 33: 
          { return createToken (sym.VECTOR);
          }
        case 73: break;
        case 3: 
          { return createToken (sym.INT);
          }
        case 74: break;
        case 43: 
          { return createToken (sym.SUBPROGRAMAS);
          }
        case 75: break;
        case 37: 
          { return createToken (sym.ESCRIBIR);
          }
        case 76: break;
        case 4: 
          { return createToken (sym.ID);
          }
        case 77: break;
        case 11: 
          { return createToken (sym.PUNTO_COMA);
          }
        case 78: break;
        case 31: 
          { return createToken (sym.ENTERO);
          }
        case 79: break;
        case 13: 
          { return createToken (sym.PUNTO);
          }
        case 80: break;
        case 28: 
          { return createToken (sym.PARA);
          }
        case 81: break;
        case 14: 
          { return createToken (sym.SUMA);
          }
        case 82: break;
        case 16: 
          { return createToken (sym.MENOR_QUE);
          }
        case 83: break;
        case 7: 
          { return createToken (sym.PARENTESIS_DER);
          }
        case 84: break;
        case 27: 
          { return createToken (sym.SINO);
          }
        case 85: break;
        case 35: 
          { return createToken (sym.BOOLEANO);
          }
        case 86: break;
        case 19: 
          { return createToken (sym.EN);
          }
        case 87: break;
        case 2: 
          { 
          }
        case 88: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
